name: Generate Icon Font
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Font
        run: |
          mkdir -p dist
          npx fantasticon@3.0.0 icons/ \
            --output dist/ \
            --name euro-icons \
            --font-types ttf woff woff2 \
            --asset-types css \
            --prefix esi \
            --selector .esi

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Auto-generate fonts and CSS" || echo "No changes to commit"
          git push
