name: Generate Icon Font
on: 
  push:
    branches:
      - main
    paths:
      - 'icons/**'
      - 'package.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          #cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Optimize SVGs
        run: npx svgo -f icons -o icons

      - name: Generate Font
        run: |
          mkdir -p dist
          npx fantasticon@3.0.0 icons/ \
            --output dist/ \
            --name euro-icons \
            --font-types ttf woff woff2 \
            --asset-types css json \
            --prefix esi \
            --selector .esi

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add icons/ dist/ # On ajoute icons/ car SVGO a modifi√© les sources
          git commit -m "chore: optimize icons and rebuild font [skip ci]" || echo "No changes"
          git push

      - name: Create Version Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
